# -*- coding: utf-8 -*-
"""sorting_hat.ipy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fADvMfu0b_yUaiILgpPWYXpsGsUDKztI
"""

gryffindor = 0
ravenclaw = 0
hufflepuff = 0
slytherin = 0
q1 = int(input("Q1) Do you like Dawn or Dusk?\n 1) Dawn \n 2) Dusk\n"))
if q1 == 1:
  gryffindor +=1
  ravenclaw +=1
elif q1 == 2:
  hufflepuff +=1
  slytherin +=1
else:
  print("Wrong input")
q2 = int(input("When I'm dead, I want peopele to remember me as:\n 1) The Good\n 2) The Great \n 3) The Wise\n 4) The Bold \n "))
if q2 == 1 :
  hufflepuff += 2
elif q2 == 2 :
  slytherin += 2
elif q2 == 3 :
  ravenclaw += 2
elif q2 == 4 :
  gryffindor += 2
else :
  print("Wrong Input")
q3 = int(input("Which Kind of instrument most pleases your rear? \n 1) The violin\n 2) The Trumpet \n 3) The piano \n 4) The drum\n"))
if q3 == 1 :
  slytherin += 4
elif q3 == 2 :
  hufflepuff += 4
elif q3 == 3 :
  ravenclaw += 4
elif q3 == 4 :
  gryffindor += 4
else:
  print("Wrong Input")

print(f" Final scores are listed below \n Ravenclaw : {ravenclaw} \n Hufflepuff : {hufflepuff} \n Slytherin : {slytherin} \n Gryffindor : {gryffindor}")
if ravenclaw > slytherin and ravenclaw > gryffindor and ravenclaw :
  print("Ravenclaw has the most points")
elif gryffindor > ravenclaw and gryffindor > slytherin and gryffindor > hufflepuff:
  print("Gryffindor has the most points")
elif hufflepuff > ravenclaw  and hufflepuff > gryffindor and hufflepuff > slytherin:
  print("Hufflepuff has the most points")
else:
  print("Slytherin has the highest points")